In [2]:
import numpy as np

a = np.array([1,2,3,4])

In [3]:
a.dtype

dtype('int32')

In [4]:
b = np.array(['a', 'b'])
b.dtype

dtype('<U1')

In [5]:
b = np.array(['a', 'b'], dtype=str)
b.dtype

dtype('<U1')

In [6]:
a = np.array([1, 2, 3], dtype=np.uint64)
b.dtype

dtype('<U1')

In [7]:
d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
d.shape

(3, 4)

In [8]:
d = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]],[[9, 10], [11, 12]]])
d.shape

(3, 2, 2)

In [9]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [10]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
np.empty(10)

array([9.69465040e-312, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 3.96641256e-061, 1.74248616e-076, 5.20940757e-090,
       4.65939627e-033, 5.56268866e-309])

In [12]:
np.zeros(3, dtype=np.float32)

array([0., 0., 0.], dtype=float32)

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((2, 3, 7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [15]:
a = np.empty((2, 3, 4))
a

array([[[9.69464537e-312, 7.41098469e-322, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 1.16096346e-028, 9.82205649e+252,
         1.11789342e+253],
        [8.20690325e+136, 1.47852184e+137, 2.87521844e+161,
         5.59943827e-067]],

       [[2.30292586e+161, 5.58132872e+252, 8.85450255e+228,
         1.24366207e+137],
        [1.76971783e+137, 3.57668621e-062, 9.79726238e-076,
         2.83712587e+137],
        [3.69745589e+093, 8.27171410e+136, 2.46631867e+179,
         3.46111160e-309]]])

In [16]:
a[0][1] = 7
a

array([[[9.69464537e-312, 7.41098469e-322, 0.00000000e+000,
         0.00000000e+000],
        [7.00000000e+000, 7.00000000e+000, 7.00000000e+000,
         7.00000000e+000],
        [8.20690325e+136, 1.47852184e+137, 2.87521844e+161,
         5.59943827e-067]],

       [[2.30292586e+161, 5.58132872e+252, 8.85450255e+228,
         1.24366207e+137],
        [1.76971783e+137, 3.57668621e-062, 9.79726238e-076,
         2.83712587e+137],
        [3.69745589e+093, 8.27171410e+136, 2.46631867e+179,
         3.46111160e-309]]])

In [17]:
a[0] + 1
a

array([[[9.69464537e-312, 7.41098469e-322, 0.00000000e+000,
         0.00000000e+000],
        [7.00000000e+000, 7.00000000e+000, 7.00000000e+000,
         7.00000000e+000],
        [8.20690325e+136, 1.47852184e+137, 2.87521844e+161,
         5.59943827e-067]],

       [[2.30292586e+161, 5.58132872e+252, 8.85450255e+228,
         1.24366207e+137],
        [1.76971783e+137, 3.57668621e-062, 9.79726238e-076,
         2.83712587e+137],
        [3.69745589e+093, 8.27171410e+136, 2.46631867e+179,
         3.46111160e-309]]])

In [18]:
a = a[0] + 1
a

array([[1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000],
       [8.00000000e+000, 8.00000000e+000, 8.00000000e+000,
        8.00000000e+000],
       [8.20690325e+136, 1.47852184e+137, 2.87521844e+161,
        1.00000000e+000]])

In [19]:
a[2] = 4.3
a

array([[1. , 1. , 1. , 1. ],
       [8. , 8. , 8. , 8. ],
       [4.3, 4.3, 4.3, 4.3]])

In [20]:
a[[0,2]]

array([[1. , 1. , 1. , 1. ],
       [4.3, 4.3, 4.3, 4.3]])

In [21]:
a = np.array( [list(range(1, 5)), list(range(5, 9)), list(range(9, 13))] )
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
a[[0,1],[0,2]]

array([1, 7])

In [23]:
a = [1, 2, 3, 4]
b = a[1:2]
print(b)
b[0] = 3
print(a, b)

[2]
[1, 2, 3, 4] [3]


In [24]:
a = np.array([1, 2, 3, 4])
b = a[1:2]
print(b)
b[0] = 3
print(a, b)

a = np.array([1, 2, 3, 4])
b = a.copy()[1:2]
print(b)
b[0] = 3
print(a, b)

[2]
[1 3 3 4] [3]
[2]
[1 2 3 4] [3]


In [26]:
a == 1

array([ True, False, False, False])

In [34]:
(a == 1) & (a == 2)

array([False, False, False, False])

In [36]:
 a[np.array([True, False, True, False])]

array([1, 3])

In [40]:
a[(a == 1) | (a == 3)]

array([1, 3])

In [45]:
a = np.eye(3)
print(a)

a.flatten()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [49]:
a = np.array([[1, 1, 1],[2, 2, 2],[3, 3, 3]])
print(a)
a.transpose()

[[1 1 1]
 [2 2 2]
 [3 3 3]]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
a = np.array([[1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3]])
print(a)
a.reshape((4, 3))
print(a)
a.reshape((2, 6))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


array([[1, 1, 1, 1, 2, 2],
       [2, 2, 3, 3, 3, 3]])

In [60]:
np.random.random()

0.08806549812476439

In [62]:
np.random.random(5)

array([0.15225752, 0.98751834, 0.56845303, 0.99890573, 0.56308068])

In [64]:
np.random.random((5, 3))

array([[0.59209649, 0.67935372, 0.75704493],
       [0.03254451, 0.91408716, 0.17069278],
       [0.62818246, 0.72481616, 0.32159578],
       [0.29172994, 0.91150632, 0.18556166],
       [0.70764849, 0.2047676 , 0.17789164]])

In [73]:
a = np.random.random((2, 3))
print(a)

b = np.random.random((2, 3))
print(b)

print( np.hstack([a, b]), np.vstack([a, b]) )

[[0.67408584 0.70292961 0.60690936]
 [0.60510631 0.72645163 0.03209241]]
[[0.83430526 0.79112819 0.19670516]
 [0.12530975 0.28316193 0.58878791]]
[[0.67408584 0.70292961 0.60690936 0.83430526 0.79112819 0.19670516]
 [0.60510631 0.72645163 0.03209241 0.12530975 0.28316193 0.58878791]] [[0.67408584 0.70292961 0.60690936]
 [0.60510631 0.72645163 0.03209241]
 [0.83430526 0.79112819 0.19670516]
 [0.12530975 0.28316193 0.58878791]]


In [79]:
c = np.array([[1, 2, 3],[4, 5, 6]])
np.prod(c)

720

In [80]:
np.prod(c, axis=0)

array([ 4, 10, 18])

In [82]:
np.prod(c, axis=1)

array([  6, 120])

In [85]:
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([5, 6, 7, 8]).reshape(2, 2)

a + b

array([[ 6,  8],
       [10, 12]])

In [87]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

In [102]:
a = np.random.random(100)
a = a * 100
a = np.array(a, dtype=int)
print(a)

print(np.percentile(a, 0))
print(np.percentile(a, 25))
print(np.percentile(a, 50))
print(np.percentile(a, 75))
print(np.percentile(a, 100))

a.sort()

print(a)

[43 46 31 10 75 13 47 84 23 38 80 74 28 18 63 44 38 68 75 73 99 36 25 82
 84 90 12 34 66 37  1 66 87 74 63 59 22 64  2 45 29 23 34 48 19 19 74 95
 76 74 51  2  9  1 20 82 11 53 17 40 19 55 89 49 98  3 53 38 32 20 96 58
 66 37 23 70 18 18 52 79  9 25 34 24 79 87 83 15  0 65 63 39 51 24  2 83
  4 23 56 44]
0.0
22.75
44.0
70.75
99.0
[ 0  1  1  2  2  2  3  4  9  9 10 11 12 13 15 17 18 18 18 19 19 19 20 20
 22 23 23 23 23 24 24 25 25 28 29 31 32 34 34 34 36 37 37 38 38 38 39 40
 43 44 44 45 46 47 48 49 51 51 52 53 53 55 56 58 59 63 63 63 64 65 66 66
 66 68 70 73 74 74 74 74 75 75 76 79 79 80 82 82 83 83 84 84 87 87 89 90
 95 96 98 99]
