In [66]:
import numpy as np

a = np.array([1,2,3,4])

In [67]:
a.dtype

dtype('int32')

In [68]:
b = np.array(['a', 'b'])
b.dtype

dtype('<U1')

In [69]:
b = np.array(['a', 'b'], dtype=str)
b.dtype

dtype('<U1')

In [70]:
a = np.array([1, 2, 3], dtype=np.uint64)
b.dtype

dtype('<U1')

In [71]:
d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
d.shape

(3, 4)

In [72]:
d = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]],[[9, 10], [11, 12]]])
d.shape

(3, 2, 2)

In [73]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [74]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [75]:
np.empty(10)

array([-1.66157655e+036, -5.22037102e-053,  4.65187659e-308,
       -2.73699648e-048, -3.81152633e-032, -1.20950425e-009,
       -1.72229181e+036, -9.84906284e-058, -1.57234264e-063,
        0.00000000e+000])

In [76]:
np.zeros(3, dtype=np.float32)

array([0., 0., 0.], dtype=float32)

In [77]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
np.zeros((2, 3, 7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [79]:
a = np.empty((2, 3, 4))
a

array([[[0., 0., 0., 0.],
        [7., 7., 7., 7.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [80]:
a[0][1] = 7
a

array([[[0., 0., 0., 0.],
        [7., 7., 7., 7.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
a[0] + 1
a

array([[[0., 0., 0., 0.],
        [7., 7., 7., 7.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [82]:
a = a[0] + 1
a

array([[1., 1., 1., 1.],
       [8., 8., 8., 8.],
       [1., 1., 1., 1.]])

In [84]:
a[2] = 4.3
a

array([[1. , 1. , 1. , 1. ],
       [8. , 8. , 8. , 8. ],
       [4.3, 4.3, 4.3, 4.3]])

In [85]:
a[[0,2]]

array([[1. , 1. , 1. , 1. ],
       [4.3, 4.3, 4.3, 4.3]])

In [105]:
a = np.array( [list(range(1, 5)), list(range(5, 9)), list(range(9, 13))] )
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a[[0,1],[0,2]]

array([1, 7])

In [108]:
a = [1, 2, 3, 4]
b = a[1:2]
print(b)
b[0] = 3
print(a, b)

[2]
[1, 2, 3, 4] [3]


In [111]:
a = np.array([1, 2, 3, 4])
b = a[1:2]
print(b)
b[0] = 3
print(a, b)

a = np.array([1, 2, 3, 4])
b = a.copy()[1:2]
print(b)
b[0] = 3
print(a, b)

[2]
[1 3 3 4] [3]
[2]
[1 2 3 4] [3]
