In [2]:
import numpy as np

x = [1,2,3]
y = [4,5,6]

print( x + y )

[1, 2, 3, 4, 5, 6]


In [4]:
print( np.array(x) + np.array(y) )

[5 7 9]


In [7]:
print( np.concatenate([np.array(x) , np.array(y)]) )

[1 2 3 4 5 6]


In [11]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2,5)

c = np.concatenate([a, b])

print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
c2 = np.concatenate([[a, b], [a, b]])
print(c2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [19]:
print(np.concatenate([[a, b], [a, b]], axis=1))
print(np.concatenate([[a, b], [a, b]], axis=2))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]
  [10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4  0  1  2  3  4]
  [ 5  6  7  8  9  5  6  7  8  9]]

 [[10 11 12 13 14 10 11 12 13 14]
  [15 16 17 18 19 15 16 17 18 19]]]


In [22]:
print( np.vstack([a,b]) )
print( np.hstack([a,b]) )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [31]:
i = np.arange(10, 121, 10)

print( np.split(i, 2) )
print( np.split(i, 6) )
# print( np.split(i, 3) )
print( np.split(i, [3,5, 9]) )


[array([10, 20, 30, 40, 50, 60]), array([ 70,  80,  90, 100, 110, 120])]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100]), array([110, 120])]
[array([10, 20, 30]), array([40, 50]), array([60, 70, 80, 90]), array([100, 110, 120])]


In [35]:
j = np.arange(10, 121, 10).reshape(3, 4)
print(j)

print( np.vsplit(j, 3) )
print( np.hsplit(j, [3, 5, 9]) )

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([[ 90, 100, 110, 120]])]
[array([[ 10,  20,  30],
       [ 50,  60,  70],
       [ 90, 100, 110]]), array([[ 40],
       [ 80],
       [120]]), array([], shape=(3, 0), dtype=int64), array([], shape=(3, 0), dtype=int64)]
