In [3]:
import numpy as np

a = np.array([i for i in range(10)]);

print(a);

[0 1 2 3 4 5 6 7 8 9]


In [7]:
aa = np.array([i for i in range(2, 11, 2)])
print(aa);

ab = np.array(range(2, 11, 2))
print(ab)

[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [8]:
print( np.arange(2, 11, 2) )

[ 2  4  6  8 10]


In [9]:
print( np.arange(10, 0, -.5) )

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5  1.   0.5]


In [11]:
s = np.arange(10)
sm = s.reshape(2, 5)
print(sm)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
s2 = np.arange(40)
s2m = s2.reshape(2, 5, 4)
print( s2m )

print( s2.reshape(2, 5, 2, 2) )

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]

  [[16 17]
   [18 19]]]


 [[[20 21]
   [22 23]]

  [[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]

  [[36 37]
   [38 39]]]]


In [18]:
print( s2m[1][2][3] )
print( s2m[1, 2, 3] )

31
31


In [26]:
print( s2[ s2 < 30 ] )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
