In [2]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print( a > 5 )
print( a[a > 5] )
a[a > 5] = 99
print( a )
print( a[ ~(a == 99) ] )
print( a[ ~(a == 99) & ( a % 2 == 0 ) ] )
print( a[ ~(a == 99) | ( a % 2 == 0 ) ] )

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[99 99 99 99 99 99]
[[ 0  1  2  3]
 [ 4  5 99 99]
 [99 99 99 99]]
[0 1 2 3 4 5]
[0 2 4]
[0 1 2 3 4 5]
