In [2]:
import numpy as np

# arr = [1, 2, 3] + 1 // 불가
# print( arr ) 

arr = np.array([1, 2, 3]) + 1
print( arr )

a = np.arange(9).reshape(3, 3)
print(a)
print( a + np.array([1, 2, 3]) )

[2 3 4]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
