In [2]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
b = np.ones(12)
print(b)

b2 = np.ones([3, 4])
print(b2)

b3 = np. ones([3, 4, 5])
print(b3)

b4 = np.zeros([3, 4])
print(b4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
c = np.eye(3)
print(c)

d = np.arange(9).reshape(3, 3)
print(d)

print( np.dot(c, d) )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [17]:
print( np.empty(5) )
print( np.full((3, 4), 50) )
print( np.linspace(2, 20, 10) )

[ 2.   6.5 11.  15.5 20. ]
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [21]:
print(a)
print( a.ravel() )
print( a.ravel(order='C') )
print( a.ravel(order='F') )



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]
