In [3]:
import numpy as np

a= np.array([[2, 3, 6, 8],[11, 13, 20, 45],[100, 193, 354, 555]]).reshape(3, 4)

print( np.mean(a) ) #average

print( np.median(a) ) # very middle value

109.08333333333333
16.5


In [17]:
print( np.std(a) )
print( np.var(a) )
print( np.sum(a) )
print( np.cumsum(a) )
print( np.argmin(a) )
print( np.argmax(a) )

print( np.any(a) )

print( np.nansum(a) )

print( a % 2 == 0 )
print( np.any( a % 2 == 0 ) )
print( np.all( a % 2 == 0 ) )


168.4797012171562
28385.409722222223
1309
[   1    4   10   18   29   42   62  107  207  400  754 1309]
0
11
True
1309
[[False False  True  True]
 [False False  True False]
 [ True False  True False]]
True
False


In [23]:
print( np.where( a % 2 == 0 ) ) #result mean : 좌표값 배열임. 만족하는 값들의 좌표값만 모아 [x1, x2, x3, ...], [y1, y2, y3, ...], ...

print( a )
print( np.where( a % 2 == 0, a, 'changed' ) ) # 만족하지 않는 값들을 바꿔줌

(array([0, 0, 1, 2, 2]), array([2, 3, 2, 0, 2]))
[[  1   3   6   8]
 [ 11  13  20  45]
 [100 193 354 555]]
[['changed' 'changed' '6' '8']
 ['changed' 'changed' '20' 'changed']
 ['100' 'changed' '354' 'changed']]


In [25]:
b = np.arange(36).reshape(3,4,3)

print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [27]:
print( np.sum(b) )
print( np.sum(b, axis=0) )
print( np.sum(b, axis=1) )
print( np.sum(b, axis=2) )

630
[[36 39 42]
 [45 48 51]
 [54 57 60]
 [63 66 69]]
[[ 18  22  26]
 [ 66  70  74]
 [114 118 122]]
[[  3  12  21  30]
 [ 39  48  57  66]
 [ 75  84  93 102]]
