In [25]:
import numpy as np
import random as rd

print( rd.randint(1, 10) )
print( rd.uniform(1, 10) )

print( rd.randrange(0, 100, 2) )

l = [i for i in range(20)]
rd.shuffle(l)
print( l )
print( rd.choice(l) )
print( rd.sample(l, 5) )

rd.seed(105)
print( rd.randint(1, 200) )

6
6.226503119740731
12
[19, 17, 8, 7, 4, 3, 15, 12, 6, 1, 11, 14, 5, 13, 2, 18, 10, 16, 9, 0]
12
[3, 1, 10, 6, 17]
152


In [31]:
print( np.random.randint(1, 10) )
print( np.random.randint(1, 10, size=(10)) )
print( np.random.randint(1, 10, size=(3, 4)) )

print( np.random.normal(1, 10, size=(3, 4)) )

5
[8 6 3 1 1 5 6 2 3 3]
[[6 6 8 4]
 [6 6 3 7]
 [9 6 1 8]]
[[13.74261289  7.21718678 14.83319451  8.551311  ]
 [17.02787802 -1.47100169 12.30955277 13.4943669 ]
 [ 4.08865372  5.82565858  0.95053976  2.15183606]]
