In [2]:
import numpy as np

a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [7]:
a = np.arange(1, 31)
print(a[::-1])

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1]


In [8]:
ar = a.reshape(5, 6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [16]:
print(ar[:, 1])
print(ar[1, :])
print(ar[1:3, 1:3])
print(ar[::2, ::2])

[ 2  8 14 20 26]
[ 7  8  9 10 11 12]
[[ 8  9]
 [14 15]]
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [17]:
b = ar.copy()
b[0] = 100
print(b)

[[100 100 100 100 100 100]
 [  7   8   9  10  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]
 [ 25  26  27  28  29  30]]


In [20]:
d3 = np.arange(30).reshape(2, 3, 5)

print(d3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [21]:
print(d3[1, :, ::-1])

[[19 18 17 16 15]
 [24 23 22 21 20]
 [29 28 27 26 25]]
